#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import re, io

SRC = r"G:/GitHub/WorldAirlinersSet/lang/chinese_simplified.lng"

# Overrides: key -> final Chinese value (corrections + newly translated + keep-as-is)
OVR = {
    # ---- GRF header ----
    "STR_GRF_DESCRIPTION": ("{ORANGE}世界航空公司整合包 (WAS){}{SILVER}该套装旨在呈现 OpenTTD 中近期与历史时期的世界各国航空公司与飞机。"
        "{}{BLACK}程序设计: {SILVER}Beardie, DJNekkid, Faddypainter, Frank, George, Rens, Huub 和 Yorick"
        "{}{BLACK}图形设计: {SILVER}Beardie, Dimme, EXTSpotter, Faddypainter, Frank, Firzafp, Getuouk, Giles, RvP93, Simozzz, Huub, Trainboy2004 和 Vlad"
        "{}大多数图形最初来自 PikkaBirds 的 AV8 套装，使用时请署名。所有贡献者信息可在 README 文件中找到。"),
    "STR_GRF_URL": "http://dev.openttdcoop.org/projects/worldairlinersset",

    # ---- Params ----
    "STR_PARAM_NAME_ENABLE_STANDARD_PLANES": "启用标准飞机",
    "STR_PARAM_DESC_ENABLE_STANDARD_PLANES": "启用所有标准飞机",

    # ---- Aeroplanes (fixes + translate) ----
    "STR_AIRV_BAC_CONCORDE": "协和式超音速客机",
    "STR_AIRV_BAE_146_100": "英国宇航 146-100",
    "STR_AIRV_BAE_146_200": "英国宇航 146-200",
    "STR_AIRV_BAE_146_300": "英国宇航 146-300",
    "STR_AIRV_BAE_146_300QT": "英国宇航 146-300QT",
    "STR_AIRV_SKYLIFT_150": "SkyLift 150",

    # ---- Livery / manufacturers fixes ----
    "STR_VLIV_WAS": "WAS 七周年纪念涂装",

    # ---- Airline corrections ----
    "STR_VLIV_AIR_AUSTRAL": "留尼汪南方航空",
    "STR_VLIV_FLYNORDIC": "飞北欧航空",
    "STR_VLIV_MALEV": "马雷夫航空",
    "STR_VLIV_MALEV_OLD": "马雷夫航空（旧）",
    "STR_VLIV_AEROLOGIC": "欧陆航空",
    "STR_VLIV_AIR_SOUTHWEST": "英国西南航空",
    "STR_VLIV_LION_AIR": "印尼狮子航空",
    "STR_VLIV_MERIDIANA": "意大利子午线航空",
    "STR_VLIV_SPANAIR": "斯潘航空",
    "STR_VLIV_ARKE_FLY": "阿克航空",
    "STR_VLIV_SAS": "北欧航空",
    "STR_VLIV_AER_ARRAN_ORIGINAL": "爱尔兰阿伦航空（原版）",
    "STR_VLIV_AER_ARRAN_RINGED_DESIGN": "爱尔兰阿伦航空（环形设计）",

    # ---- Airline new translations ----
    "STR_VLIV_AEROPOSTAL": "委内瑞拉航空邮政",
    "STR_VLIV_AIR_AFRIQUE": "非洲航空",
    "STR_VLIV_AIR_CONTRACTORS": "空运承包商航空",
    "STR_VLIV_AIR_ONE": "第一航空",
    "STR_VLIV_ALBAWINGS": "阿尔巴之翼航空",
    "STR_VLIV_AMC_AVIATION": "AMC 航空",
    "STR_VLIV_ANADOLUJET": "阿纳多卢航空",
    "STR_VLIV_ARKAS": "阿尔卡斯航空",
    "STR_VLIV_AVIOGENEX": "阿维奥基内克斯航空",
    "STR_VLIV_AZERBAIJAN_AIRLINES": "阿塞拜疆航空",
    "STR_VLIV_AZUR_AIR": "蔚蓝航空",
    "STR_VLIV_AZUR_AIR_UKRAINE": "蔚蓝航空（乌克兰）",
    "STR_VLIV_BA_WORLD_CARGO": "英国航空货运",
    "STR_VLIV_BADR_AIRLINES": "巴德尔航空",
    "STR_VLIV_BAL_BASHKIRIAN": "巴什基尔航空",
    "STR_VLIV_BALAIR": "巴尔航空",
    "STR_VLIV_BALKAN_BULGARIAN": "巴尔干保加利亚航空",
    "STR_VLIV_BALKAN_BULGARIAN_OLD": "巴尔干保加利亚航空（旧）",
    "STR_VLIV_BAVARIA_GERMANAIR": "巴伐利亚德国航空",
    "STR_VLIV_BELAVIA": "白俄罗斯航空",
    "STR_VLIV_BELAVIA_OLD": "白俄罗斯航空（旧）",
    "STR_VLIV_BIMAN_BANGLADESH_AIRLINES": "孟加拉航空",
    "STR_VLIV_BINTER_CANARIAS": "宾特航空",
    "STR_VLIV_BIRGENAIR": "碧根航空",
    "STR_VLIV_BLUE1": "蓝一航空",
    "STR_VLIV_BLUE_AIR": "蓝色航空",
    "STR_VLIV_BLUEBIRD_AIRWAYS": "蓝鸟航空",
    "STR_VLIV_BMI_BABY": "BMI 宝贝航空",
    "STR_VLIV_BOAC": "英国海外航空",
    "STR_VLIV_BRANIFF": "布兰尼夫国际航空",
    "STR_VLIV_BRITAIR": "不列颠航空（法国航空）",
    "STR_VLIV_BRITISH_AIRTOURS": "英国航空旅游",
    "STR_VLIV_BRITISH_AIRWAYS_CITYFLYER": "英国航空城市快线",
    "STR_VLIV_BRITISH_AIRWAYS_LANDOR": "英国航空（Landor）",
    "STR_VLIV_BRITISH_AIRWAYS_LANDOR_RED": "英国航空（Landor 红）",
    "STR_VLIV_BRITISH_AIRWAYS_NEGUS": "英国航空（Negus）",
    "STR_VLIV_BRITISH_AIRWAYS_UNION_FLAG": "英国航空（米字旗）",
    "STR_VLIV_BRITISH_AIRWAYS_UNION_FLAG_COMAIR": "英国航空 米字旗（Comair）",
    "STR_VLIV_BRITISH_CALEDONIAN": "英国喀里多尼亚航空",
    "STR_VLIV_BRUSSELS_AIRLINES": "布鲁塞尔航空",
    "STR_VLIV_BULGARIA_AIR": "保加利亚航空",
    "STR_VLIV_BUZZ": "蜂鸣航空",
    "STR_VLIV_CARGOLUX": "卢森堡货运航空",
    "STR_VLIV_CARPATAIR": "喀尔巴阡航空",
    "STR_VLIV_CATHAY_PACIFIC": "国泰航空",
    "STR_VLIV_CATHAY_PACIFIC_CARGO": "国泰航空货运",
    "STR_VLIV_CHANNEL_EXPRESS": "海峡快运航空",
    "STR_VLIV_CHINA_AIRLINES": "中华航空",
    "STR_VLIV_CHINA_AIRLINES_CARGO": "中华航空货运",
    "STR_VLIV_CLAN_MEGA": "麦加部族航空",
    "STR_VLIV_CLICKAIR": "点击航空",
    "STR_VLIV_CONDOR": "神鹰航空",
    "STR_VLIV_CONDOR_BERLIN": "神鹰柏林航空",
    "STR_VLIV_CONVIASA": "委内瑞拉国家航空",
    "STR_VLIV_COPA_AIRLINES": "巴拿马航空",
    "STR_VLIV_CORENDON_AIRLINES": "科伦登航空",
    "STR_VLIV_CROATIA_AIRLINES": "克罗地亚航空",
    "STR_VLIV_CUBANA_DE_AVIACION": "古巴航空",
    "STR_VLIV_CYGNUS": "天鹅航空",
    "STR_VLIV_CYPRUS_AIRWAYS": "塞浦路斯航空",
    "STR_VLIV_CZECH_AIRLINES": "捷克航空",
    "STR_VLIV_DAN_AIR_LONDON": "伦敦丹航空",
    "STR_VLIV_DBA": "DBA 航空",
    "STR_VLIV_DELTA_AIR_LINES": "达美航空",
    "STR_VLIV_DELTA_CONNECTION": "达美连接航空",
    "STR_VLIV_DRAGONAIR": "港龙航空",
    "STR_VLIV_DUTCH_ANTILLES_EXPRESS": "荷属安的列斯快运航空",
    "STR_VLIV_EASTERN_AIR_LINES": "美国东方航空",
    "STR_VLIV_EASYJET": "易捷航空",
    "STR_VLIV_ECAIR": "刚果航空",
    "STR_VLIV_EGYPT_AIR": "埃及航空",
    "STR_VLIV_EL_AL_ISRAEL_AIRLINES": "以色列航空",
    "STR_VLIV_ELLINAIR": "希腊航空",
    "STR_VLIV_EMIRATES": "阿联酋航空",
    "STR_VLIV_EMIRATES_SKYCARGO": "阿联酋航空货运",
    "STR_VLIV_ENTER_AIR": "安特航空",
    "STR_VLIV_ESTONIAN": "爱沙尼亚航空",
    "STR_VLIV_ETF_AIRLINES": "ETF 航空",
    "STR_VLIV_ETHIOPIAN_AIRLINES": "埃塞俄比亚航空",
    "STR_VLIV_ETIHAD_AIRWAYS": "阿提哈德航空",
    "STR_VLIV_ETIHAD_AIRWAYS_ABU_DHABI_FORMULA_1": "阿提哈德航空（阿布扎比一级方程式）",
    "STR_VLIV_EUROATLANTIC_AIRWAYS": "欧洲大西洋航空",
    "STR_VLIV_EUROLOT": "欧罗罗特航空",
    "STR_VLIV_EUROATLANTIC": "欧洲大西洋航空",
    "STR_VLIV_EUROPEAN_AIRCHARTER": "欧洲航空包机",
    "STR_VLIV_EUROWINGS": "欧洲之翼航空",
    "STR_VLIV_FARNAIR_EUROPE": "法恩欧洲航空",
    "STR_VLIV_FLYBE": "弗莱比航空",
    "STR_VLIV_FLYEGYPT": "飞埃及航空",
    "STR_VLIV_FLYGLOBESPAN": "环球飞鹰航空",
    "STR_VLIV_FLYR": "Flyr 航空",
    "STR_VLIV_FUTURA": "未来航空",
    "STR_VLIV_GERMANWINGS": "德国之翼航空",
    "STR_VLIV_GIRJET": "吉尔航空",
    "STR_VLIV_GOL": "高尔航空",
    "STR_VLIV_GREAT_DANE": "大丹航空",
    "STR_VLIV_GULF_AIR": "海湾航空",
    "STR_VLIV_HAPAG_LLOYD": "赫伯罗特航空",
    "STR_VLIV_HELLENIC_IMPERIAL_AIRWAYS": "希腊帝国航空",
    "STR_VLIV_HELLO": "哈罗航空",
    "STR_VLIV_HELVETIC_AIRWAYS": "赫勒维蒂克航空",
    "STR_VLIV_HIGHLAND_EXPRESS": "高地快运航空",
    "STR_VLIV_HISKY": "海天航空",
    "STR_VLIV_HISPANIA": "西班牙航空",
    "STR_VLIV_HOP": "HOP! 航空",
    "STR_VLIV_IBERWORLD": "伊比利亚世界航空",
    "STR_VLIV_KMV": "KMV 航空",
    "STR_VLIV_LA_COMPAGNIE": "法国商务航空",
    "STR_VLIV_LAGUNAIR": "拉古纳航空",
    "STR_VLIV_MALMO_AVIATION_SVENSK_FOOTBALL": "马尔默航空（瑞典足球）",
    "STR_VLIV_MEXICANA": "墨西哥航空",
    "STR_VLIV_MYWINGS": "我的翅膀航空",
    "STR_VLIV_PALMAIR": "帕尔马航空",
    "STR_VLIV_PEGAS_FLY": "飞马飞航空",
    "STR_VLIV_PEOPLEXPRESS": "人民快运航空",
    "STR_VLIV_PLUS_ULTRA": "更进一步航空",
    "STR_VLIV_POBEDA": "胜利航空",
    "STR_VLIV_PORTUGALIA": "葡萄牙航空",
    "STR_VLIV_PRECISION_AIR_SERVICES": "精确航空",
    "STR_VLIV_PRIMERA_AIR": "普里梅拉航空",
    "STR_VLIV_PRIVILEGE_STYLE": "特权航空",
    "STR_VLIV_PSA": "太平洋西南航空",
    "STR_VLIV_QANTASLINK": "澳洲链接航空",
    "STR_VLIV_QANTASLINK_PINK_RIBBON": "澳洲链接航空（粉红丝带）",
    "STR_VLIV_QATAR_AIRWAYS_CARGO": "卡塔尔航空货运",
    "STR_VLIV_REGIONAL_CARGO": "区域货运航空",
    "STR_VLIV_ROSSIYA_AIRLINES": "罗斯尼亚航空",
    "STR_VLIV_ROSSIYA_AIRLINES_OLD": "罗斯尼亚航空（旧）",
    "STR_VLIV_ROYAL_BRUNEI_AIRLINES": "文莱皇家航空",
    "STR_VLIV_ROYAL_FLIGHT": "皇家航空",
    "STR_VLIV_ROYAL_JORDANIAN": "约旦皇家航空",
    "STR_VLIV_ROYAL_MAIL": "英国皇家邮政",
    "STR_VLIV_RWANDAIR": "卢旺达航空",
    "STR_VLIV_RYANAIR": "瑞安航空",
    "STR_VLIV_SABENA": "萨贝纳航空",
    "STR_VLIV_SAMOA_AIRWAYS": "萨摩亚航空",
    "STR_VLIV_SATA": "SATA 亚速尔航空",
    "STR_VLIV_SATENA": "SATENA 航空",
    "STR_VLIV_SAUDI_ARABIAN_AIRLINES": "沙特阿拉伯航空",
    "STR_VLIV_SKYMARK_AIRLINES": "天马航空",
    "STR_VLIV_SKYUP": "天空航空",
    "STR_VLIV_SKYWEST": "天西航空",
    "STR_VLIV_SLOK_AIR": "斯洛克航空",
    "STR_VLIV_SLOKAIR": "斯洛克国际航空",
    "STR_VLIV_SMALL_PLANET": "小星球航空",
    "STR_VLIV_SMART_WINGS": "智能之翼航空",
    "STR_VLIV_SOMON_AIR": "索蒙航空",
    "STR_VLIV_SOUTH_AFRICAN_AIRWAYS": "南非航空",
    "STR_VLIV_SOUTH_AFRICAN_CARGO": "南非货运航空",
    "STR_VLIV_SOUTH_WEST_GOLD": "西南航空（金色）",
    "STR_VLIV_SOUTHWEST_AIRLINES": "西南航空",
    "STR_VLIV_SPANTAX": "西班牙包机航空",
    "STR_VLIV_SRILANKAN_AIRLINES": "斯里兰卡航空",
    "STR_VLIV_SUDAN_AIRWAYS": "苏丹航空",
    "STR_VLIV_SUNWING": "太阳之翼航空",
    "STR_VLIV_SURINAM_AIRWAYS": "苏里南航空",
    "STR_VLIV_SWIFTAIR": "迅捷航空",
    "STR_VLIV_SWISSAIR": "瑞士航空",
    "STR_VLIV_SWISS_AIR": "瑞士航空",
    "STR_VLIV_SWISS": "瑞士国际航空",
    "STR_VLIV_SWISS_INTERNATIONAL_AIRLINES": "瑞士国际航空",
    "STR_VLIV_SYRIAN_ARAB_AIRLINES": "叙利亚航空",
    "STR_VLIV_TAAG_ANGOLA_AIRLINES": "安哥拉航空",
    "STR_VLIV_TAE": "TAE 航空",
    "STR_VLIV_TAM_AIRLINES": "TAM 航空",
    "STR_VLIV_TAP": "葡萄牙航空",
    "STR_VLIV_TAROM": "罗马尼亚航空",
    "STR_VLIV_TASSILI_AIRLINES": "塔西利航空",
    "STR_VLIV_THAI_AIRWAYS_INTERNATIONAL": "泰国国际航空",
    "STR_VLIV_THOMAS_COOK": "托马斯·库克航空",
    "STR_VLIV_THOMSON_AIRWAYS": "汤姆森航空",
    "STR_VLIV_TRANSAERO": "环宇航空",
    "STR_VLIV_TRAVEL_SERVICE": "旅行服务航空",
    "STR_VLIV_TUNISAIR": "突尼斯航空",
    "STR_VLIV_TURKISH_AIRLINES": "土耳其航空",
    "STR_VLIV_TURKISH_AIRLINES_CARGO": "土耳其航空货运",
    "STR_VLIV_TURKMENISTAN_AIRLINES": "土库曼斯坦航空",
    "STR_VLIV_TWA": "环球航空",
    "STR_VLIV_UKRAINE_INTERNATIONAL_AIRLINES": "乌克兰国际航空",
    "STR_VLIV_ULS_CARGO": "ULS 货运航空",
    "STR_VLIV_URAL_AIRLINES": "乌拉尔航空",
    "STR_VLIV_UZBEKISTAN_AIRWAYS": "乌兹别克斯坦航空",
    "STR_VLIV_V_AUSTRALIA": "V 澳大利亚航空",
    "STR_VLIV_VARIG": "巴里格航空",
    "STR_VLIV_VIASA": "委内瑞拉国际航空",
    "STR_VLIV_WAMOS": "瓦莫斯航空",
    "STR_VLIV_WESTJET": "西捷航空",
    "STR_VLIV_WIDEROE": "威德罗航空",
}

pat = re.compile(r'^(\s*)(STR_[A-Za-z0-9_]+)(\s*):(.*)$')

out = []
n_changed = 0
with io.open(SRC, encoding="utf-8") as f:
    for line in f:
        # keep newline style
        raw = line.rstrip("\n")
        m = pat.match(raw)
        if m and m.group(2) in OVR:
            key = m.group(2)
            prefix = m.group(1) + key + m.group(3) + ":"
            newval = OVR[key]
            out.append(prefix + newval)
            n_changed += 1
        else:
            out.append(raw)

with io.open(SRC, "w", encoding="utf-8") as f:
    f.write("\n".join(out) + "\n")

print("Changed/added entries:", n_changed)
